<?php
/**
 * Created by PhpStorm.
 * User: Moh Roufiq Azmy
 * Date: 5/31/2017
 * Time: 11:47 PM
 */
use yii\db\Schema;
use yii\db\Migration;

class m310517_000002_create_user extends Migration
{

    public function up()
    {
//        return parent::up(); // TODO: Change the autogenerated stub

        $tables = Yii::$app->db->schema->getTableNames();
        $dbType = $this->db->driverName;
        $tableOptions_mysql = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB";
        $tableOptions_mssql = "";
        $tableOptions_pgsql = "";
        $tableOptions_sqlite = "";
        /* MYSQL */
        if (!in_array('user', $tables))  {
            if ($dbType == "mysql") {
                $this->createTable('{{%user}}', [
                    'id' => 'INT(11) NOT NULL AUTO_INCREMENT',
                    0 => 'PRIMARY KEY (`id`)',
                    'username' => 'VARCHAR(32) NOT NULL',
                    'auth_key' => 'VARCHAR(32) NULL DEFAULT \'simeulue\'',
                    'password_hash' => 'VARCHAR(255) NOT NULL',
                    'password_reset_token' => 'VARCHAR(255) NULL',
                    'email' => 'VARCHAR(255) NOT NULL',
                    'status' => 'SMALLINT(6) NOT NULL DEFAULT \'10\'',
                    'created_at' => 'INT(11) NOT NULL',
                    'updated_at' => 'INT(11) NOT NULL',
                ], $tableOptions_mysql);
            }
        }


        /*
         * tambah user default untuk role admin, petugas, dan subject matter
         */
        $this->execute('SET foreign_key_checks = 0');
        $this->insert('{{%user}}',['id'=>'1','username'=>'admin','auth_key'=>'UOGugWr4naCBl2ohBh6no9SEL8sFZ3Ky','password_hash'=>'$2y$13$cjTwfH0rhiJjtpo4cUuOqunGtBQGt3RgWULMvopqUsB1b220rDU/.','password_reset_token'=>'','email'=>'bps1101@bps.go.id','status'=>'10','created_at'=>'1492858761','updated_at'=>'1496249079']);
        $this->insert('{{%user}}',['id'=>'2','username'=>'testing','auth_key'=>'simeulue','password_hash'=>'$2y$13$mQTwz90VDNCiRkPIHSOiu.8J63MizUaUow3g8VH6jw/LYq1eb3ZAq','password_reset_token'=>'','email'=>'testing@mail.com','status'=>'10','created_at'=>'1494429408','updated_at'=>'1496249188']);
        $this->insert('{{%user}}',['id'=>'3','username'=>'sosial','auth_key'=>'simeulue','password_hash'=>'$2y$13$TLhXYtm6UOf1JQqzTjx6ju4lxuP3Nd/JAk6s.7mTW6A0kAkLerz4m','password_reset_token'=>'','email'=>'sosial1100@bps.go.id','status'=>'10','created_at'=>'1494429496','updated_at'=>'1496249204']);
        $this->execute('SET foreign_key_checks = 1;');

    }

    public function down()
    {
//        return parent::down(); // TODO: Change the autogenerated stub

        $this->execute('SET foreign_key_checks = 0');
        $this->execute('DROP TABLE IF EXISTS `user`');
        $this->execute('SET foreign_key_checks = 1;');

    }
}